import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/context/Provider";
import { I18nProvider } from "@/context/i18nContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <I18nProvider>
          <Provider>
            <body className="min-h-full flex flex-col">{children}</body>
          </Provider>
        </I18nProvider>
        {/* <footer>Esto es un footer y se ve en todas las vistas</footer> */}
      </html>
    </>
  );
}
